### ISSUE TITLE
Todo:

### ISSUE THREAD

**Issue by forrestlaine** [forrestlaine/VehicleSim#1]
- [x] Proper shutdown of sockets / visualization
- [x] Camera-follow sink for simulation
- [x] Wheel slip model
- [x] Creation, loading and vis of maps
- [x] Port sensor models from old sim
- [ ] Define challenge metrics / monitoring
